/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_djf_pedometerdataencrypt_NDKUtils */

#ifndef _Included_com_djf_pedometerdataencrypt_NDKUtils
#define _Included_com_djf_pedometerdataencrypt_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_djf_pedometerdataencrypt_NDKUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_djf_pedometerdataencrypt_NDKUtils_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_djf_pedometerdataencrypt_NDKUtils
 * Method:    dataAesEncrypt
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_djf_pedometerdataencrypt_NDKUtils_dataAesEncrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_djf_pedometerdataencrypt_NDKUtils
 * Method:    dataAesDecrypt
 * Signature: ([B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_djf_pedometerdataencrypt_NDKUtils_dataAesDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
